### ISSUE TITLE
Propose release of 2.0

### ISSUE THREAD

**Issue by mallim** [pnowy/NativeCriteria#13]
Hi 

Is there any timeline for version 2.0.0 release?

Thanks
Ian Lim

**Comment by pnowy** [comment]
Hi,

you could always take a look at milestones section:

https://github.com/pnowy/NativeCriteria/milestones

Initially I've planned to release the 2.0 version at the end of Semptember. Unfortunately do to my engagement to new commercial project the release has been postponed to the end of the year.

I hope that I will finish the changes to end of December but I cannot promise it (one more time - a lot of other duties).

Regards,
Przemyslaw
