### ISSUE TITLE
How to use NativeCriteria on this sql?

### ISSUE THREAD

**Issue by mallim** [pnowy/NativeCriteria#15]
Hi

I'm not sure how to use NativeCriteria to form the FROM clause for the sql statement below:

````sql
SELECT 
    productID,
    productName,
    categoryName,
    companyName AS supplier
FROM
    products
INNER JOIN
    categories ON categories.categoryID = products.categoryID
INNER JOIN
    suppliers ON suppliers.supplierID = products.supplierID
````

Is there a test case or something which I can refer to ?

Thanks

**Comment by pnowy** [comment]
Hi,

I will add the test case with example.

**Comment by pnowy** [comment]
Hi,

I've extended test db schema (please take a look at https://github.com/pnowy/NativeCriteria/tree/develop/nativeCriteria-test - there is a db schema diagram) and prepared the test with query from question.

You will find the example on the https://github.com/pnowy/NativeCriteria/blob/develop/nativeCriteria-test/src/test/java/com/github/pnowy/nc/queries/SelectWithJoinsTest.java and test **shouldSelectProductsWithCategoriesAndSuppliers**

I hope this is it what you expected. If you have any further questions do not hesitate to ask.
