### ISSUE TITLE
How to perform ORDER BY NEWID()

### ISSUE THREAD

**Issue by mallim** [pnowy/NativeCriteria#18]
Hi

May I know how to construct a sql as below?

````
SELECT * FROM aTable ORDER BY NEWID()
````

I tried to use NativeOrderExps but notice that it didn't take in a sql expression.

Thanks
Ian Lim

**Comment by pnowy** [comment]
Hi,

the only way for this moment to use the custom order clause will be following:

```
NativeCriteria nc = createNativeCriteria("ADDRESS", "a");
nc.setOrder(NativeExps.order().add("NEWID()", NativeOrderExp.OrderType.ASC));
CriteriaResult result = nc.criteriaResult();
```

See the commit referenced to the ticket. I've added there additional SQL Server profile and usage of it (I've tested it on SQL Server 2012).

On the future I'm planning to add the possibility to add the custom SQL expression on each place of NativeCriteria API and it will be the preferred way for that kind of actions (see ticket https://github.com/pnowy/NativeCriteria/issues/6).
