### ISSUE TITLE
Mixed parameter strategies error

### ISSUE THREAD

**Issue by AntonBolotov** [pnowy/NativeCriteria#36]
Hello,

I have found a bug in expressions. NativeNotLikeExp, NativeNotILikeExp. They don`t use varName variable. As a result I am getting error
javax.persistence.PersistenceException: org.hibernate.engine.query.ParameterRecognitionException: Mixed parameter strategies - use just one of named, positional or JPA-ordinal strategy

**Comment by pnowy** [comment]
Fixed in version 3.0.1

**Comment by AntonBolotov** [comment]
Thanks!

**Comment by pnowy** [comment]
Your are welcome!
