### ISSUE TITLE
Allow to add SQL expression on each place of the criteria API

### ISSUE THREAD

**Issue by pnowy** [pnowy/NativeCriteria#6]
Sometime happens that we want to add the custom SQL on some specific place of query. It would be good to support that kind of approach and allows the user to add implementation of expression on each place of API

**Comment by pnowy** [comment]
The possibility to use custom SQL parts has been added. The examples are available on the class: CustomSqlQueriesPartsTest

**Comment by mallim** [comment]
Hi there

This is a nice feature, may I know when will this be officially release ? Thanks.

**Comment by pnowy** [comment]
Hi, I moved the documentation changes (I want to migrate to http://couscous.io/ engine) to version 2.1 so I think the release of 2.0 will be available in the coming days.

**Comment by pnowy** [comment]
Hello,

version 2.0 (http://mvnrepository.com/artifact/com.github.pnowy.nc/nativeCriteria-core/2.0) is available on maven central. Any remarks & bugs are welcome!
